In [2]:
import numpy as np
arr=np.random.randint(1,100, size=(10,5)) #sample 10 Feature 5

In [3]:
arr.shape

(10, 5)

In [4]:
#to reshape row and column 
b=arr.reshape(5,10)

In [10]:
arr.shape
arr.ndim
b

array([[84, 70, 74, 79, 34, 66, 86, 26, 66, 51],
       [58, 19,  9, 19, 38, 32, 73, 53, 72, 14],
       [38, 21,  8, 90, 29, 85, 48, 24, 26, 86],
       [64, 70, 19, 45, 24, 47, 28, 34, 80, 58],
       [28, 98, 19, 41, 67, 62, 85, 99, 35, 13]])

In [11]:
#to change it into 1dim
flatten=b.flatten() #flatten convert it into 1 dim and combine row
print(flatten)
flatten

[84 70 74 79 34 66 86 26 66 51 58 19  9 19 38 32 73 53 72 14 38 21  8 90
 29 85 48 24 26 86 64 70 19 45 24 47 28 34 80 58 28 98 19 41 67 62 85 99
 35 13]


array([84, 70, 74, 79, 34, 66, 86, 26, 66, 51, 58, 19,  9, 19, 38, 32, 73,
       53, 72, 14, 38, 21,  8, 90, 29, 85, 48, 24, 26, 86, 64, 70, 19, 45,
       24, 47, 28, 34, 80, 58, 28, 98, 19, 41, 67, 62, 85, 99, 35, 13])

In [13]:
#too comnbine column wise
column_wise_flattening=np.ravel(b,order='f')
column_wise_flattening

array([84, 58, 38, 64, 28, 70, 19, 21, 70, 98, 74,  9,  8, 19, 19, 79, 19,
       90, 45, 41, 34, 38, 29, 24, 67, 66, 32, 85, 47, 62, 86, 73, 48, 28,
       85, 26, 53, 24, 34, 99, 66, 72, 26, 80, 35, 51, 14, 86, 58, 13])

In [24]:
a=np.random.randint(1,10, size=(3,5))
b=np.random.randint(20,30, size=(3,5))
print(a)
print(b)

[[8 1 9 2 2]
 [7 1 1 9 2]
 [1 2 5 9 2]]
[[25 26 28 25 24]
 [27 20 27 20 20]
 [22 21 27 21 20]]


### concatenate

In [28]:
con_row=np.concatenate((a,b),axis=0)
print(con_row)
# to concaneate row wise column should be same
#to concantenate coloumn wise row should be same

[[ 8  1  9  2  2]
 [ 7  1  1  9  2]
 [ 1  2  5  9  2]
 [25 26 28 25 24]
 [27 20 27 20 20]
 [22 21 27 21 20]]


In [27]:
con_column=np.concatenate((a,b),axis=1)
print(con_column)

[[ 8  1  9  2  2 25 26 28 25 24]
 [ 7  1  1  9  2 27 20 27 20 20]
 [ 1  2  5  9  2 22 21 27 21 20]]


In [30]:
mat=np.array([[10,20,30,40]
              ,[30,40,50,60]])
transpose=mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]
 [40 60]]


### Array split


In [38]:
a=np.random.randint(1,100, size=(10,))
splitted_array=np.array_split(a,3)
print(splitted_array)
#to equal split we use split()

[array([77, 86, 42, 54]), array([44,  7,  3]), array([54, 24, 81])]


## Arithmetic Operators and Mathematical Functions

In [6]:
import numpy as np
#fatser for vectorization
x=np.array([10,20,30,40])
y=np.array([1,2,3,4,])
add=x+y
print(add)
remainder=x % y
print(remainder)
sub = x-y 
print(sub)

[11 22 33 44]
[0 0 0 0]
[ 9 18 27 36]


In [15]:
#mathematical fuctions
#trigonometry
#sin cos tan takes value in radia
sin_values=np.sin(x)
print(sin_values)
cos_values=np.cos(x)
print(cos_values)
tan_values=np.tan(y)
print(tan_values)
deg_conv=np.rad2deg(x)
print(deg_conv)
#deg=

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]


In [18]:
#log'
base_10_log=np.log(x)
print(base_10_log)
sqrt=np.sqrt(x)
print(sqrt)

[2.30258509 2.99573227 3.40119738 3.68887945]
[3.16227766 4.47213595 5.47722558 6.32455532]


In [24]:
s=np.sum(x)
print(x)
cumu=np.cumsum(x)
print(cumu)

[10 20 30 40]
[ 10  30  60 100]


## LOgical FUnction

In [32]:
#comoarison >,< <=,>=,==,==!
x=np.array([10,20,30,40])
y=np.array([1,2,3,4,])
greater_than=x>y
print(greater_than)
print(x>25)
print(x[x>20])
equal=x==y
print(equal)
# all() if all true
#any () if any true
print(np.all(greater_than))
print(np.any(equal))


[ True  True  True  True]
[False False  True  True]
[30 40]
[False False False False]
True
False


## Sorting

# inplace
x=np.array([20,30,10,40,50,45])
z=x.copy()
print(z)
z.sort()
print(z)

In [44]:
#copy sorting
print(x)
sort_array=np.sort(x)
print(sort_array)
print(x)

[20 30 10 40 50 45]
[10 20 30 40 45 50]
[20 30 10 40 50 45]


In [49]:
#2D arrayy sorting
mat=np.array([[20,10,30],[8,5,3]])
#horizon axis=1
hor_sort=np.sort(mat,axis=1)
print(hor_sort)
ver_sort=np.sort(mat,axis=0)
print(ver_sort)

[[10 20 30]
 [ 3  5  8]]
[[ 8  5  3]
 [20 10 30]]


## Searching

In [50]:
print(x)

[20 30 10 40 50 45]


In [56]:
#np.where(condition, x,y) if true x, otherwise replace with y
index=np.where(x==40)
print(index)
index=np.where(x >40,x,0) #those which are not greater than 40 will convert to zero or remains the same
print(index)

(array([3], dtype=int64),)
[ 0  0  0  0 50 45]


In [57]:
print(mat)

[[20 10 30]
 [ 8  5  3]]


In [61]:
index=np.where(mat<8)
print(index) #col 1 row 1, col 1 row 2

(array([1, 1], dtype=int64), array([1, 2], dtype=int64))


In [65]:
maximum_value=np.argmax(x)
print(maximum_value) #return index
min_value=np.argmin(x)
print(min_value)

4
2


## Counting

In [9]:
import numpy as np
a=np.random.randint(1,100,size=(100,))
print(a)

[78 21 53 63 66 81 88 37 92 75 55 62 11 14 77 17 20 84  2 32 65 88 44 34
  3 75 46 81 10 42 11 73 70 11 31 99 60 90 34 15 24 19 47 94 81  3 63 31
  8 29 78 42 12 49 38 34 72 94 80 47 90 40 27 12 48 35 96  1 35  5 75 43
 70 91  7 72 68  7 57  2 39 44 70 51 21  1 10 47 62 74 28 54  3 53 92 58
 70 37 23 74]


In [10]:
value_greater_than_40=np.count_nonzero(a>40)
print(value_greater_than_40)

57


In [14]:
unique_value,count=np.unique(a,return_counts=True)
print(unique_value)
print(count)

[ 1  2  3  5  7  8 10 11 12 14 15 17 19 20 21 23 24 27 28 29 31 32 34 35
 37 38 39 40 42 43 44 46 47 48 49 51 53 54 55 57 58 60 62 63 65 66 68 70
 72 73 74 75 77 78 80 81 84 88 90 91 92 94 96 99]
[2 2 3 1 2 1 2 3 2 1 1 1 1 1 2 1 1 1 1 1 2 1 3 2 2 1 1 1 2 1 2 1 3 1 1 1 2
 1 1 1 1 1 2 2 1 1 1 4 2 1 2 3 1 2 1 3 1 2 2 1 2 2 1 1]


# statistical function

In [24]:
# data loading
data =np.genfromtxt('student_scores.csv', delimiter=',',skip_header=1,usecols=(1,2,3))
print(data)

[[78. 85. 82.]
 [65. 72. 70.]
 [90. 88. 95.]
 [55. 60. 58.]
 [82. 79. 85.]
 [74. 69. 71.]
 [88. 92. 90.]
 [61. 65. 63.]
 [95. 98. 97.]
 [70. 75. 73.]
 [84. 81. 86.]
 [59. 62. 60.]
 [76. 80. 78.]
 [68. 70. 72.]
 [91. 89. 93.]
 [64. 67. 66.]
 [87. 85. 88.]
 [72. 74. 70.]
 [79. 83. 81.]
 [66. 68. 69.]]


In [27]:
Englis_marks=data[::,:1]
print(Englis_marks)
print(Englis_marks.T)

[[78.]
 [65.]
 [90.]
 [55.]
 [82.]
 [74.]
 [88.]
 [61.]
 [95.]
 [70.]
 [84.]
 [59.]
 [76.]
 [68.]
 [91.]
 [64.]
 [87.]
 [72.]
 [79.]
 [66.]]
[[78. 65. 90. 55. 82. 74. 88. 61. 95. 70. 84. 59. 76. 68. 91. 64. 87. 72.
  79. 66.]]


In [43]:
max_englis=np.max(Englis_marks)
print(max_englis)
min_english=np.min(Englis_marks)
print(min_english)
median_english=np.median(Englis_marks)
print(median_english)
#std
std_eng=np.std(Englis_marks)
var_eng=np.var(Englis_marks) # square of std
print(var_eng)
mean_eng=np.mean(Englis_marks)
print(mean_eng)
largest_value_index=np.argmax(Englis_marks)
print(largest_value_index)

95.0
55.0
75.0
129.35999999999999
75.2
8


## Correlation


In [2]:
import numpy as np
study_hours=np.array([2,3,4,5,6,7])
exam_scores=np.array([90,80,70,60,50,40])
data=np.array([study_hours, exam_scores])     
print(data)
correlation=np.corrcoef(data)
print(correlation) 

[[ 2  3  4  5  6  7]
 [90 80 70 60 50 40]]
[[ 1. -1.]
 [-1.  1.]]


## Linear algebra

In [11]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([
    [7,8],
    [9,10],
    [11,12]])
dot_product=np.dot(A,B) # A column and B column should be same
print(dot_product) #matrix multiplication
#trace
print(np.trace(A))


[[ 58  64]
 [139 154]]
6


In [17]:
#Determinents
sq_matrix=np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
det_of_sq=np.linalg.det(sq_matrix)
print(det_of_sq)
#rank
rank_sq=np.linalg.matrix_rank(sq_matrix)
print(rank_sq)

6.66133814775094e-16
2
