# Num= Numerical

In [2]:
arr=[1,2,3]
print(arr*5) # it prints the array 5 times instead of multiply each elements
arr=[x*5 for x in arr]
arr # now it * each element using loop

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


[5, 10, 15]

In [3]:
#same operation using numpy

In [5]:
import numpy as np
arr1=np.array([1,2,3])
arr1=arr1*5
print(arr1)


[ 5 10 15]


In [6]:
import numpy as np
arr2=np.array([5,6,7])
arr2=arr2*6
print(arr2)

[30 36 42]


# nd array


In [20]:
import numpy as np
# id arrray
arr1=np.array([1,2,3,4,5])
print(type(arr1))
print(arr1.ndim) # dimension check

#2d array
arr2=np.array([[1,2,3,],[4,5,6]])
print(arr2.ndim)

# 3d arrray
arr3=np.array([
   [ [1,2,3,],
    [4,5,6]],  # first row 
    [[1,2,3,],
     [4,5,6]] # second row
])
arr3
print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
3


## Array attributes

In [24]:
#dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(2, 2, 3)
int32
int32
int32
5
6
12


# nd array data type

In [32]:
arr=np.array([1,2,34])
print(arr.dtype)
arr=np.array([1.5,2.3,4.5])
print(arr.dtype)

int32
float64


In [34]:
arr=np.array([1,2,3.4])
print(arr.dtype) # upcasting,2 can turn into 2.0
#upcasted to string
arr=np.array([1,2,'3']) # int to flot,float to string but string to int cannot
print(arr.dtype)

float64
<U11


 # selecting a data type for an array

In [38]:
arr=np.array([1,2,3.4,300])
print(arr.dtype)
arr=arr.astype(np.int16)
print(arr.dtype)

float64
int16


In [46]:
arr=np.array([1,2,3.4,300],dtype=np.int16)
print(arr.dtype)
print(arr)

arr=arr.astype(np.int32)
print(arr.dtype) #changed datatype
#error
#arr=np.array([1,2,3,'hello'],dtype=np.float64)

int16
[  1   2   3 300]
int32


# nd array creation from existing data

In [51]:
#list
lst=[10,20,30,40,40.5]
arr=np.array(lst,dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)


[10 20 30 40 40]
<class 'numpy.ndarray'>
int32


In [53]:
mixed_lst=[10,True,'hello',4.5]
arr=np.array(mixed_lst)
print(arr)
print(type(arr))
print(arr.dtype)   #converted to string


['10' 'True' 'hello' '4.5']
<class 'numpy.ndarray'>
<U32


In [56]:
matrix=np.array([[1,2,3,],[4,5,6]])
arr=np.array(matrix)
print(arr)
print(type(arr))
print(arr.dtype)
print(matrix.ndim)
print(matrix.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int32
2
(2, 3)


In [58]:
#tuuple
tpl=(1,2,3,4)
arr=np.array(tpl)
print(arr)
print(type(arr))
print(arr.dtype)
print(matrix.ndim)
print(matrix.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
int32
2
(2, 3)


In [62]:
#set
set={1,3,4}
arr=np.array(list(set)) # if we didnot convert to list it will take the set as element and take it as object
arr=arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(matrix.ndim)
print(matrix.shape)

[1 3 4]
<class 'numpy.ndarray'>
int16
2
(2, 3)


In [82]:
#dictionary
dc={'a':20,'b':30,'c':40}
print(type(dc))
keys=dc.keys()
print(keys)

values=dc.values()
print(values)

items=dc.items()
print(items)

#keys to nd array
arr=np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(matrix.ndim)
print(matrix.shape)

# values to nd arrray
arr=np.array(list(values))
print(arr)
arr=arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(matrix.ndim)
print(matrix.shape)

<class 'dict'>
dict_keys(['a', 'b', 'c'])
dict_values([20, 30, 40])
dict_items([('a', 20), ('b', 30), ('c', 40)])
['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
2
(2, 3)
[20 30 40]
<class 'numpy.ndarray'>
int16
2
(2, 3)


In [84]:
#items to array
arr=np.array(list(items))
print(arr)

print(type(arr))
print(arr.dtype)
print(matrix.ndim)
print(matrix.shape)

[['a' '20']
 ['b' '30']
 ['c' '40']]
<class 'numpy.ndarray'>
<U11
2
(2, 3)


# Array creation with random values

In [88]:
#np.random.ran(shape)
arr=np.random.rand(2,3)
print(arr)

print(type(arr))
print(arr.dtype)
print(matrix.ndim)
print(matrix.shape)

[[0.18020518 0.57261686 0.23629744]
 [0.23519832 0.59724336 0.46978688]]
<class 'numpy.ndarray'>
float64
2
(2, 3)


In [92]:
#np.random.ran(starting point,endpoint(shape))
arr=np.random.randint(1,5,(10,10)) #to get innt value
print(arr)

print(type(arr))
print(arr.dtype)
print(matrix.ndim)
print(matrix.shape) 

[[2 3 2 3 4 4 2 4 2 1]
 [2 4 1 3 4 4 1 3 1 1]
 [1 1 2 1 1 4 3 3 1 1]
 [2 2 1 3 1 1 1 2 2 4]
 [2 3 2 4 3 1 2 2 3 2]
 [1 2 3 1 1 4 1 3 3 1]
 [1 3 2 3 3 3 2 2 2 4]
 [3 4 2 3 2 4 1 3 4 4]
 [1 3 3 4 3 2 1 3 2 4]
 [1 1 3 1 4 2 4 2 4 3]]
<class 'numpy.ndarray'>
int32
2
(2, 3)


In [95]:
#np.random.uniform(starting point,endpoint(shape))
arr=np.random.uniform(1,5,(10,10)) #to get innt value
print(arr)

print(type(arr))
print(arr.dtype)
print(matrix.ndim)
print(matrix.shape) 

[[4.0752038  4.47140994 2.90827468 4.27637362 3.71706526 3.41951454
  2.48140368 3.71601026 3.10149327 1.85073773]
 [2.61265035 2.86550814 4.43452965 1.33919222 2.19415563 1.54997895
  3.10712983 2.5086613  1.60813726 1.9288607 ]
 [4.97979446 1.02703778 4.838633   4.25432518 4.01673168 3.18222485
  4.46835568 1.92944041 4.29539238 3.44836352]
 [4.09183848 1.75297128 4.26901444 3.50071826 3.13454427 1.4105017
  3.64217852 4.40720022 3.86327865 1.49047687]
 [4.079374   4.89457313 4.93367399 1.16068314 3.71609988 4.05790128
  2.40423521 4.51536494 1.51134916 3.1130218 ]
 [1.28823981 2.56390837 1.82987006 1.59255884 4.62609996 1.63308823
  2.48929443 4.34168682 2.370055   3.62982561]
 [2.86779114 4.16693054 2.74607604 2.05138629 2.40121846 3.34002486
  4.63807221 3.49526588 3.17874113 4.13521569]
 [4.33097505 2.93912678 3.59232104 2.80166742 3.33594305 4.72470419
  3.02890215 3.38431179 3.29421586 1.67499594]
 [3.80191041 1.10905334 4.63137571 2.60343481 3.07681635 3.59608709
  1.58143501 

# Array Creation With Range Functions

In [14]:
#np.arrange(firsst,end,step) similar to range function
import numpy as np
arr= np.arange(1,10,1)
mat=arr.reshape(3,3) #reshaped the array
print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape) 

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int32
1
(9,)


In [18]:
#np.linespace(start,end,point)
arr= np.linspace(1,16,10) #get the same space ,distance is same foe each point 

print(arr)

print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape) 

[ 1.          2.66666667  4.33333333  6.          7.66666667  9.33333333
 11.         12.66666667 14.33333333 16.        ]
<class 'numpy.ndarray'>
float64
1
(10,)


In [24]:
#np.logspace(start,end,value)
arr= np.logspace(0,4,4) # 4 indcates 10^0 to 10^ 4 
#we can change the base
arr= np.logspace(0,4,4,base=2)
print(arr)

print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape) 

[ 1.          2.5198421   6.34960421 16.        ]
<class 'numpy.ndarray'>
float64
1
(4,)


# indexing and slicing

In [34]:
import numpy as np
# id arrray
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1[2]) #indexing
arr1[2]=100 #changing value
print(arr1)
print(arr1[2])


[1 2 3 4 5]
3
[  1   2 100   4   5]
100
[[1 2 3]
 [4 5 6]]


In [9]:
#2d array
arr2=np.array([[1,2,3,],[4,5,6]])
print(arr2)
print(arr2[1][1]) #row 1 , column 1
arr2[0][2]=100
print(arr2)

[[1 2 3]
 [4 5 6]]
5
[[  1   2 100]
 [  4   5   6]]


# slicing

In [46]:
#1d=arr[start:end:step]
import numpy as np
# id arrray
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
print(arr1[1:9:2])

[ 1  2  3  4  5  6  7  8  9 10]
[2 4 6 8]


In [55]:
#2d slicing
#arr[row_start:row_end:end,column_start,column_end,end]
#print(arr2)
print(arr2[0:1 ,]) #row 0
print(arr2[1: ,]) #row 1
#getting a column
print(arr2[::,0:1]) #c0
print(arr2[::,1:2]) #c1

[[  1   2 100]]
[[4 5 6]]
[[1]
 [4]]
[[2]
 [5]]


In [2]:
import numpy as np
# id arrray
arr1=np.array([1,2,3,4,5])
print(arr1)
arr1_mod=arr1[1:4]
print(arr1_mod)
arr1_mod[0]=100
print(arr1_mod) #if we chnage arr1_mod , arr1 also changed(view)
print(arr1)

[1 2 3 4 5]
[2 3 4]
[100   3   4]
[  1 100   3   4   5]


In [3]:
arr1_mod=arr1[1:4].copy()
arr1_mod[2]=200
print(arr1_mod)
print(arr1) #remaining the same (copy)

[100   3 200]
[  1 100   3   4   5]


## Advance Indexing

In [7]:
lst=np.array([10,20,30,40])
values=lst[[0,3]]
print(values)

[10 40]


In [13]:
print(arr2)
print(arr2[[0,1] ,[1,2]])
print(arr2[arr2>2]) #greater than 2

[[  1   2 100]
 [  4   5   6]]
[2 6]
[100   4   5   6]


In [6]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
#iteration
for i in arr:
      print(i)
for i in np.nditer(arr):
    print(i)


[10 20 30]
[40 50 60]
10
20
30
40
50
60
